# -*- coding: utf-8 -*-
"""DFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NrcUhZ6mzLCyhenaRUSH7c97Mr6MiSS8
"""

'''Depth First Search uses STACK AND RECURSION
'''
#import defaultdict
from collections import defaultdict
def dfs(graph,start,visited,path):
    path.append(start)
    visited[start]=True
    for neighbour in graph[start]:
       #type ur code here
    return path
graph=defaultdict(list)
n,e=map(int,input().split())
for i in range(e):
   #type ur code here
    graph[v].append(u)
#print(graph)
start='A'
visited=defaultdict(bool)
 #type ur code here
traversedpath=dfs(graph,start,visited,path)
print(traversedpath)